### ISSUE TITLE
bug: gas estimate in sendSafely is overridden

### ISSUE THREAD

**Issue by liamzebedee** [keep-network/tbtc.js#26]
I discovered today, some implementations of Web3 providers will modify the sendParams you pass in to `estimateGas` (ew, gross). For example, they will set `sendParams.gas = undefined`, which will break any gas estimate we pass in here -

https://github.com/keep-network/tbtc.js/blob/2072eaffae3e76ba2ec0590a7145ac18944fc505/src/EthereumHelpers.js#L117-L120

I suspect this was the cause of my out-of-gas revert on the internal Keep network. Changing the order fixed it, I'll submit a PR later.

**Comment by Shadowfiend** [comment]
Goodness gracious, and I'm sure they don't bother cloning either. This is what `delete` is for… If you're going to mutate state you could at least mutate it correctly! Lol.

Anyway, fix sounds good and easy.

**Comment by Shadowfiend** [comment]
Actually, I wonder if, knowing this, we don't just pass a clone of the `sendParams` to `estimateGas` using [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign), i.e. `estimateGas(Object.assign({}, sendParams))` with a little comment about why we're doing something so terrible.

**Comment by liamzebedee** [comment]
@Shadowfiend mmm that's a nice idea. Noting also that the modified params also included `.data` (!), which was somewhat baffling.

**Comment by Shadowfiend** [comment]
> Noting also that the modified params also included `.data` (!)

Oh goodness…… <_<
