### ISSUE TITLE
Expose confirmation events and current confirmation count during funding/redemption

### ISSUE THREAD

**Issue by Shadowfiend** [keep-network/tbtc.js#30]
Right now, though we have promises to the states before and after the right number of confirmations are received, there is no direct access to the current number of seen confirmations or to update that number as new confirmations come in.

**Comment by Shadowfiend** [comment]
@ironng this is really a “whoever grabs it first” situation, I think. It would probably pay to start with a brief blurb here about how we intend on achieving it, though.

**Comment by ironng** [comment]
@Shadowfiend What if we change [`BitcoinHelpers.Transaction.waitForConfirmations` ](https://github.com/keep-network/tbtc.js/blob/3a1687d7ab83cb14f29367c48a17390a6a63ecd1/src/BitcoinHelpers.js#L345) to accept a third parameter `onNewBlock`? It would be a callback triggered in the inner `checkConfirmations` function that is passed to (`ethereumClient.onNewBlock(checkConfirmations)`)? The callback can provide the current number of confirmations as its first param. 

Then for the deposit and redemption sides we can add expose new events tied to this callback...maybe?

**Comment by Shadowfiend** [comment]
This sounds like a good move. We can use an `EventEmitter` for those events, maybe?

**Comment by ironng** [comment]
`EventEmitter` sounds good 👍
