### ISSUE TITLE
ElectrumHelpers.findWithClient can't find fundingTransaction post-redemption

### ISSUE THREAD

**Issue by liamzebedee** [keep-network/tbtc.js#33]
Spotted this while implementing fraud proofs in #25. I suspect this is because we use `electrumClient.getUnspentToScript`. After the redemption tx is mined on Bitcoin, the funding UXTO is thereby spent, and hence this method returns no funding transaction. 

## Steps to reproduce:

 1. Create deposit
 2. Fund deposit
 3. Mint TBTC
 4. Redeem deposit
 5. Revert Ganache to step #2, Deposit ACTIVE state.

## Expected behaviour:

Despite the Ganache testchain being reverted, we should still be able to get the fundingTransaction from Electrum.

**Comment by Shadowfiend** [comment]
That `findWithClient` doesn't find it is by design, though the name isn't great for it. Could you give more detail on when you need to look up the already-spent funding UTXO?

**Comment by liamzebedee** [comment]
> though the name isn't great for it. 

Ah yeah. 

> Could you give more detail on when you need to look up the already-spent funding UTXO?

**Comment by Shadowfiend** [comment]
So interestingly, I think we can get this from the deposit 🤔 We expose `getUTXOInfo` [for testing](https://github.com/keep-network/tbtc/blob/1bbfabd00ce60af73830748faa7a68e928360889/solidity/contracts/test/deposit/TestDeposit.sol#L188-L190) right now, I wonder if it's worth exposing this as `getFundingInfo` or something like that as a public view function on the deposit.

**Comment by liamzebedee** [comment]
> We expose getUTXOInfo for testing right now, I wonder if it's worth exposing this as getFundingInfo or something like that as a public view function on the deposit.

Yeah, let's expose this. I spotted it but it was just before launch.

**Comment by Shadowfiend** [comment]
We handled this in a different way by exposing the funding info from tbtc, so we're going to lean on that for now.
