### ISSUE TITLE
Fix publish to NPM so we can require()

### ISSUE THREAD

**Issue by liamzebedee** [keep-network/tbtc.js#4]
* package.json
   * `name` should be @keep-network/tbtc.js
   * `main` should point to an existing file

After that, we should be able to do `import TBTC from '@keep-network/tbtc'`

**Comment by Shadowfiend** [comment]
Whelp it turns out I'd been a dumb and had an `index.js` file untracked in my local fs.

Fixed that, `name` was updated a little while ago as well.

If you can confirm we're good on version 0.6.6 and close the issue I'd be super appreciative! :heart:
