### ISSUE TITLE
new wires for tbtc.js - dApp UI / UX 

### ISSUE THREAD

**Issue by creckhow** [keep-network/tbtc.js#40]

**Comment by Shadowfiend** [comment]
tbtc.js is the JS library behind the dApp and has no wireframes. The repository for the dApp is tbtc-dapp, where an issue for this already exists (https://github.com/keep-network/tbtc-dapp/issues/217).

**Comment by creckhow** [comment]
yeah I thought that too, but these came directly from @mhluongo 's notes, so I put it in as is -- is this a typo or did you mean something different around tbtc.js Matt?
